### ISSUE TITLE
.bash_profileにshellモジュールが使えない

### ISSUE THREAD

**Issue by fujifujifuji** [fujifujifuji/ansible-playbook#1]
```
- name: set environment variable
  shell: '{{item.cmd}}'
  with_items:
    - cmd: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    - cmd: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    - cmd: source ~/.bash_profile
```
